// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecaqkdgjmnxwoeywhqhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjYXFrZGdqbW54d29leXdocWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjQ2MTQsImV4cCI6MjA3MjkwMDYxNH0.C89DpRjdB7RiAcefvswBvXYu_NqDny_VLrwQA3YWx2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});